[jki_lib_smo_dictionary]
state = "new requirement found"
ever-used = true
is-used = true
installed = "1.1.0.6"

[jki_lib_state_machine]
state = "new requirement found"
ever-used = true
is-used = true
installed = "2018.0.7.45"

[jki_statemachineobjects]
state = "new requirement found"
ever-used = true
is-used = true
installed = "1.4.0.69"

[oglib_file]
state = "new requirement found"
ever-used = true
is-used = true
installed = "4.0.1.22"

[oglib_time]
state = "new requirement found"
ever-used = true
is-used = true
installed = "4.0.1.3"

[oglib_variantconfig]
state = "new requirement found"
ever-used = true
is-used = true
installed = "4.0.0.5"
